apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazel-remote.fullname" . }}
  labels:
    {{- include "bazel-remote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portGrpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "bazel-remote.selectorLabels" . | nindent 4 }}
