apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-cache-server
spec:
  template:
    spec:
      containers:
      - name: cache-server
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: CACHE_PRUNING_MAX_CACHE_SIZE_GB
          value: "2000"
        - name: CACHE_PRUNING_INTERVAL_HOURS
          value: "12"
        - name: CACHE_PRUNING_RETENTION_DAYS
          value: "14"
