apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: build-cache-server-hpa
  namespace: build-cache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: build-cache-server
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Object
    object:
      metric:
        name: grpc_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
      describedObject:
        apiVersion: v1
        kind: Service
        name: build-cache-server
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: build-cache-server-pdb
  namespace: build-cache
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: build-cache-server
